version: 2
updates:
    - package-ecosystem: "npm"
      directory: "/"
      schedule:
          interval: "weekly"
      reviewers:
          - "eXodes"
      commit-message:
          prefix: "build:"
