name: Check Code
on:
    pull_request:
    push:
        branches:
            - master

jobs:
    check-linter:
        name: Linter
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup node
              uses: actions/setup-node@v2
              with:
                  node-version: '14.17.5'

            - name: Install dependencies
              run: npm ci

            - name: Run linters
              run: npm run lint

    check-build:
        needs:
            - check-linter
        name: Build
        runs-on: ubuntu-18.04
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup node
              uses: actions/setup-node@v2
              with:
                  node-version: '14.17.5'

            - name: Install dependencies
              run: npm ci

            - name: Check build script
              run: npm run build
